---
- name: Gather IOS-XE Facts
  hosts: sandbox
  connection: local
  
  tasks:
    - name: Gather IOS Facts
      ios_facts:
        provider:
          host: 1.1.1.1
          port: 8181
          username: cisco
          password: cisco

    - name: What is the IOS OS version?
      debug:
        var: ansible_net_version

    - name: What is the hostname?
      debug:
        var: ansible_net_hostname

#### OTHER USEFUL VARS
# ansible_net_config - running-config
# ansible_net_model
# ansible_net_serialnum
# ansible_net_imagem
# ansible_net_all_ipv4_addresses
# ansible_net_all_ipv6_addresses
# ansible_net_neighbors
# ansible_net_interfaces
# ansible_net_memfree_mb
# ansible_net_memtotal_mb